src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 20)]
    private $reference;

    #[ORM\Column(type: 'string', length: 100)]
    private $libelle;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $prix_reference;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $ordre_affichage;

    #[ORM\Column(type: 'string', length: 255)]
    private $image_rep;

    #[ORM\ManyToOne(targetEntity: Famille::class, inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private $famille;

    #[ORM\ManyToOne(targetEntity: Taxe::class)]
    private $taxe;

    #[ORM\OneToMany(mappedBy: 'produitref', targetEntity: Article::class)]
    private $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrixReference(): ?int
    {
        return $this->prix_reference;
    }

    public function setPrixReference(?int $prix_reference): self
    {
        $this->prix_reference = $prix_reference;

        return $this;
    }

    public function getOrdreAffichage(): ?int
    {
        return $this->ordre_affichage;
    }

    public function setOrdreAffichage(?int $ordre_affichage): self
    {
        $this->ordre_affichage = $ordre_affichage;

        return $this;
    }

    public function getImageRep(): ?string
    {
        return $this->image_rep;
    }

    public function setImageRep(string $image_rep): self
    {
        $this->image_rep = $image_rep;

        return $this;
    }

    public function getFamille(): ?Famille
    {
        return $this->famille;
    }

    public function setFamille(?Famille $famille): self
    {
        $this->famille = $famille;

        return $this;
    }

    public function getTaxe(): ?Taxe
    {
        return $this->taxe;
    }

    public function setTaxe(?Taxe $taxe): self
    {
        $this->taxe = $taxe;

        return $this;
    }
    public function __toString(){
        return $this->libelle;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setProduitref($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getProduitref() === $this) {
                $article->setProduitref(null);
            }
        }

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use App\Entity\Taxe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('reference', TextType::class,['attr' => [
        'class' => 'form-control'
    ],])
            ->add('libelle', TextType::class,['attr' => [
                'class' => 'form-control'
            ],])
            ->add('description', TextType::class,['attr' => [
                'class' => 'form-control'
            ],])
            ->add('prix_reference',IntegerType::class,['attr' => [
                'class' => 'form-control'
            ],])
            ->add('ordre_affichage',IntegerType::class,['attr' => [
                'class' => 'form-control'
            ],])
            ->add('image_rep', TextType::class,['attr' => [
                'class' => 'form-control'
            ],])
            ->add('famille')
           ->add('taxe')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Famille;
use App\Entity\Produit;
use App\Form\FamilleType;
use App\Form\ProduitType;
use App\Repository\FamilleRepository;
use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/produit')]
class ProduitController extends AbstractController
{
    #[Route('/', name: 'app_produit_index')]
    public function index(ProduitRepository $produitRepository, Request $request,FamilleRepository $familleRepository): Response
    {
        $famillesp = $familleRepository->famillePrime();

        $searchTerm = $request->query->get('q');
        $searchResult= $produitRepository->recherche($searchTerm);

        if ($request->query->get('preview')) {
            return $this->render('produit/_resultatRecherche.html.twig', [
                'resultats' => $searchResult,
            ]);
        }
        return $this->render('produit/index.html.twig',[
            'resultats'=>$searchResult,
            'searchTerm' => $searchTerm,
            'famillesp'=>$famillesp,
            //'produits' => $produitRepository->findAll(),
        ]);
    }

//    #[Route('/{libelle}', name: 'app_produit_details')]
//    public function details(Produit $produit): Response
//    {
//        return $this->render('produit/details.html.twig', compact('produit'));
//    }

    #[Route('/new', name: 'app_produit_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProduitRepository $produitRepository): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $produitRepository->add($produit, true);
            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
            }

        return $this->renderForm('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }
//    #[Route('/new', methods: ['GET', 'POST'])]
//    public function new(Request $request, ProduitRepository $produitRepository): Response
//    {
//        $produit = new Produit();
//        $form = $this->createForm(ProduitType::class, $produit);
//        $form->handleRequest($request);
//
//        if ($form->isSubmitted() && $form->isValid()) {
//            $produitRepository->add($produit, true);
//            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
//        }
//
//        return $this->renderForm('produit/index.html.twig', [
//            'produits' => $produitRepository->findAll(),
//        ]);
//    }

}

templates/produit/_form.html.twig
<div class="container">
    {%  form_theme form 'foundation_5_layout.html.twig' %}
{{ form_start(form) }}
    <div class="form-control">
        <div class="col">
            {{ form_row(form.libelle) }}
            {{ form_row(form.reference) }}
            {{ form_row(form.description) }}
            {{ form_row(form.prix_reference) }}



        </div>

    {{ form_widget(form) }}
    </div>
<button class="btn btn-info">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

</div>

templates/produit/_resultatRecherche.html.twig
<div class="list-group">
    {% for product in resultats %}
        <a class="list-group-item list-group-item-action"
           href="{{ path('app_produit_index', { id: product.id }) }}">
            {{ product.libelle }}
        </a>
    {% else %}
        <div class="list-group-item">No results found!</div>
    {% endfor %}
</div>

templates/produit/details.html.twig
{% extends "base.html.twig" %}

{% block title %}Détails de {{ produit.libelle }}{% endblock %}

{% block body %}
    <h1>Détails de {{ produit.libelle }}</h1>
{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProduitController!{% endblock %}

{% block body %}
     <h1>Liste des produits</h1>

 <h1>Produit</h1>

    <div class="container-fluid">
        <form class="d-flex">
           <div    class="input-group"
            {{ stimulus_controller('search-preview', {
                url: path('app_produit_index') }) }}>

            <input name="q" value="{{ searchTerm }}"
                    placeholder="rechercher par nom ou référence"
                    type="search" class="form-control"
                    data-action="search-preview#onSearchInput">
            rechercher</input>
           </div>
            <div class="search-preview"
                 data-search-preview-target="result">
            </div>
        </form>
    </div>

    <div class="btn-group" role="group" aria-label="Basic example">
        {% for famille in famillesp %}
        <button type="button" class="btn btn-secondary">{{ famille.libelle }}</button>
        {% endfor %}
    </div>

    <div class="container my-5">
        <a class="btn btn-primary" href="{{ path('app_produit_new') }}">Créer un nouveau produit</a>
    </div>
<style type="text/css">
    .card-horizontal {
        display: flex;
        flex: 1 1 auto;
    }
</style>

    <div class="container-fluid">
        {% for result in resultats %}
        <div class="row">
            <div class="col-12 mt-3">
                <div class="card">
                    <div class="card-horizontal">
                        <div class="img-square-wrapper">
                            <img class="" src="{{ result.imageRep }}" alt="Card image cap">
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">{{ result.Libelle }}</h4>
                            <p class="font-weight-bold"> {{ result.reference }} </p>
                            <p class="card-text"> {{ result.prixReference }} €  </p>
                        </div>
                        <div class="card-body">
                            <p class="card-text"> {{ result.description }}  </p>
                        </div>
                        <div class="card-body">
                            <div class="position-absolute top-50 end-0 ms-5 mb-10">
                                <a href="#" class="btn btn-danger my-1">Supprimer</a>
                                <a href="#" class="btn btn-primary my-1 ms-2 mr-2">Consulter</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">famille : {{ result.famille }}</small>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}

templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau produit{% endblock %}

{% block body %}
    <h1>Création d'un nouveau produit</h1>


    {{ include('produit/_form.html.twig') }}

    <a href="{{ path('app_produit_index') }}">back to list</a>

{% endblock %}