src/Entity/Taxe.php
<?php

namespace App\Entity;

use App\Repository\TaxeRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TaxeRepository::class)]
class Taxe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $libelle;

    #[ORM\Column(type: 'float')]
    private $taux_taxe;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getTauxTaxe(): ?float
    {
        return $this->taux_taxe;
    }

    public function setTauxTaxe(float $taux_taxe): self
    {
        $this->taux_taxe = $taux_taxe;

        return $this;
    }
    public function __toString(){
        return $this->libelle;
    }
}

src/Form/TaxeType.php
<?php

namespace App\Form;

use App\Entity\Taxe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class TaxeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('libelle')
            ->add('taux_taxe')
            ->add('save', SubmitType::class,[
                'attr'=>['data-action'=>"click->hello#greet"]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Taxe::class,
        ]);
    }
}

src/Controller/TaxeController.php
<?php

namespace App\Controller;

use App\Entity\Taxe;
use App\Form\TaxeType;
use App\Repository\TaxeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\TaxeService;

#[Route('/taxe')]
class TaxeController extends AbstractController
{
   /*  #[Route('/', name: 'app_taxe_index', methods: ['GET','POST'])]
    public function index_backup(TaxeRepository $taxeRepository): Response
    {
        return $this->render('taxe/index.html.twig', [
            'taxes' => $taxeRepository->findAll(),
        ]);
    } */
     #[Route('/', name: 'app_taxe_index', methods: ['GET','POST'])]
    public function index(RequestStack $requestStack,TaxeRepository $taxeRepository,TaxeService $taxeservice): Response
    {
        $taxe = new Taxe();
        $request = $requestStack->getMainRequest();
        $taxeForm = $this->createForm(TaxeType::class);
        $taxeForm->handleRequest($request);


        return $this->render('taxe/index.html.twig', [
            'form' => $taxeForm->createView(),
            'taxes' => $taxeRepository->findAll(),
        ]);
    }

    

    #[Route('/new', name: 'app_taxe_new', methods: ['GET', 'POST'])]
    public function new(Request $request, TaxeRepository $taxeRepository): Response
    {
        $taxe = new Taxe();
        $form = $this->createForm(TaxeType::class, $taxe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $taxeRepository->add($taxe, true);

            return $this->redirectToRoute('app_taxe_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('taxe/new.html.twig', [
            'taxe' => $taxe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_taxe_show', methods: ['GET'])]
    public function show(Taxe $taxe): Response
    {
        return $this->render('taxe/show.html.twig', [
            'taxe' => $taxe,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_taxe_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Taxe $taxe, TaxeRepository $taxeRepository): Response
    {
        $form = $this->createForm(TaxeType::class, $taxe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $taxeRepository->add($taxe, true);

            return $this->redirectToRoute('app_taxe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('taxe/edit.html.twig', [
            'taxe' => $taxe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_taxe_delete', methods: ['POST'])]
    public function delete(Request $request, Taxe $taxe, TaxeRepository $taxeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$taxe->getId(), $request->request->get('_token'))) {
            $taxeRepository->remove($taxe, true);
        }

        return $this->redirectToRoute('app_taxe_index', [], Response::HTTP_SEE_OTHER);
    }

}

templates/taxe/_delete_form.html.twig
<form method="post" action="{{ path('app_taxe_delete', {'id': taxe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ taxe.id) }}">
    <button class="btn">Delete</button>
</form>

templates/taxe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Taxe{% endblock %}

{% block body %}
    <h1>Edit Taxe</h1>

    {{ include('taxe/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_taxe_index') }}">back to list</a>

    {{ include('taxe/_delete_form.html.twig') }}
{% endblock %}

templates/taxe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Taxe index{% endblock %}

{% block body %}
    <h1>Taxe index</h1>
       

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Libelle</th>
                <th>Taux_taxe</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for taxe in taxes %}
            <tr>
                <td>{{ taxe.id }}</td>
                <td>{{ taxe.libelle }}</td>
                <td>{{ taxe.tauxTaxe }}%</td>
                <td>
                    <a href="{{ path('app_taxe_show', {'id': taxe.id}) }}">show</a>
                    <a href="{{ path('app_taxe_edit', {'id': taxe.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<div class="container mt-5 mb-5" style="max-width: 800px;">
        <div class="row">
            <div class="card p-3">
                <div class="col">
                   
                </div>
            </div>
        </div>
    </div>


    <a href="{{ path('app_taxe_new') }}">Create new</a>

{% endblock %}

templates/taxe/index_backup.html.twig
{% extends 'base.html.twig' %}

{% block title %}Taxe index{% endblock %}

{% block body %}
    <h1>Taxe index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Libelle</th>
                <th>Taux_taxe</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for taxe in taxes %}
            <tr>
                <td>{{ taxe.id }}</td>
                <td>{{ taxe.libelle }}</td>
                <td>{{ taxe.tauxTaxe }}</td>
                <td>
                    <a href="{{ path('app_taxe_show', {'id': taxe.id}) }}">show</a>
                    <a href="{{ path('app_taxe_edit', {'id': taxe.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    

    <a href="{{ path('app_taxe_new') }}">Create new</a>
{% endblock %}

templates/taxe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Taxe{% endblock %}

{% block body %}
    <h1>Create new Taxe</h1>

    {{ include('taxe/_form.html.twig') }}

    <a href="{{ path('app_taxe_index') }}">back to list</a>
    
{% endblock %}

templates/taxe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Taxe{% endblock %}

{% block body %}
    <h1>Taxe</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ taxe.id }}</td>
            </tr>
            <tr>
                <th>Libelle</th>
                <td>{{ taxe.libelle }}</td>
            </tr>
            <tr>
                <th>Taux_taxe</th>
                <td>{{ taxe.tauxTaxe }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_taxe_index') }}">back to list</a>

    <a href="{{ path('app_taxe_edit', {'id': taxe.id}) }}">edit</a>

    {{ include('taxe/_delete_form.html.twig') }}
{% endblock %}