src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 100)]
    private $name_complete;

    #[ORM\Column(type: 'string', length: 255)]

    #[Assert\Length(['min' => 9,'max' => 14,])]
    private $numero_siret;
    #[ORM\Column(type: 'string', length: 255)]
    private $nom_entreprise;

    #[ORM\Column(type: 'string', length: 255)]
    private $adresse;

    #[ORM\Column(type: 'boolean')]
    private $estValide;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNameComplete(): ?string
    {
        return $this->name_complete;
    }

    public function setNameComplete(string $name_complete): self
    {
        $this->name_complete = $name_complete;

        return $this;
    }

    public function getNumeroSiret(): ?string
    {
        return $this->numero_siret;
    }

    public function setNumeroSiret(string $numero_siret): self
    {
        $this->numero_siret = $numero_siret;

        return $this;
    }

    public function getNomEntreprise(): ?string
    {
        return $this->nom_entreprise;
    }

    public function setNomEntreprise(string $nom_entreprise): self
    {
        $this->nom_entreprise = $nom_entreprise;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function isEstValide(): ?bool
    {
        return $this->estValide;
    }

    public function setEstValide(bool $estValide): self
    {
        $this->estValide = $estValide;

        return $this;
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;


use App\Entity\User;
use App\Entity\Taxe;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/client')]
class ClientController extends AbstractController
{
    #[Route('/', name: 'app_client_index', methods: ['GET','POST'])]
    public function index(UserRepository $clientRepository): Response
    {
        return $this->render('client/index.html.twig', [
            'clients' => $clientRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_client_valid', methods: ['GET','POST'])]
    public function validate(User $client, UserRepository $clientRepository ): Response
    {
        $client->setEstValide(true);
        $clientRepository ->add($client,true);
        return $this->render('client/index.html.twig', [
            'clients' => $clientRepository->findAll(),
        ]);
    }
}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Clients administration!{% endblock %}

{% block body %}
    <h1>Liste des clients</h1>

    <h1>Client</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Nom complet</th>
            <th>numero siret</th>
            <th>Entreprise</th>
            <th>adresse</th>
            <th>validation</th>
            <th> </th>
        </tr>
        </thead>

        <tbody>
        <div class="container-primaire">
            {% for client in clients %}
                {#  {% if produit.parent == null %}   #}

                <tr>
                    <td>{{ client.id }}</td>
                    <td>{{ client.nameComplete }}</td>
                    <td>{{ client.numeroSiret }}</td>
                    <td>{{ client.nomEntreprise}}</td>
                    <td>{{ client.adresse }}</td>
                    {% if client.estValide %}
                    <td>  <p> est validé</p> </td>
                    <td>   <a href="#"> Striker ce client </a></td>
                        {% else %}
                    <td>   <p> non validé</p>   </td>
                    <td> <a href="{{ path('app_client_valid', {'id': client.id}) }}"> valider ce client</a></td>
                        {% endif%}


                    <td>
                    </td>
                </tr>


                <tr>
                    <td colspan="5">no records found</td>
                </tr>
            {% endfor %}
        </div>
        </tbody>
    </table>
{% endblock %}